import json
import urllib.request
import urllib.error
from typing import Dict, Any, List
from backend.config import OLLAMA_API_URL, OLLAMA_LLM_MODEL

class SecurityAnalystAgent:
    """
    Security Analyst Agent.
    A senior SOC analyst that performs reasoning, threat detection, classification,
    MITRE mapping, and provides recommendations based on raw log/alert inputs and RAG context.
    """
    def __init__(self, model_name: str = OLLAMA_LLM_MODEL, api_url: str = OLLAMA_API_URL):
        self.model_name = model_name
        self.api_url = api_url.rstrip("/")

    def analyze(self, security_input: str, retrieved_context: str) -> Dict[str, Any]:
        """
        Runs threat analysis on security inputs, incorporating RAG context from the Knowledge Agent.
        Returns a structured agent response.
        """
        system_prompt = (
            "You are a senior SOC analyst and cybersecurity expert.\n"
            "Your task is to analyze security inputs (logs, alerts, IOCs, reports) and incorporate any retrieved technical context to perform cybersecurity reasoning.\n"
            "You MUST return a JSON object with the following schema:\n"
            "{\n"
            '  "threat_detected": "Detailed explanation of the security threat, or \'None\' if normal traffic.",\n'
            '  "classification": "Specific category of attack (e.g., SQL Injection, Brute Force, Cross-Site Scripting, DDoS, Ransomware, Normal, etc.)",\n'
            '  "severity": "High" | "Medium" | "Low" | "Info",\n'
            '  "mitre_mapping": [\n'
            '     {\n'
            '       "tactic": "MITRE ATT&CK Tactic (e.g., Initial Access, Execution, Persistence, Defense Evasion, Credential Access)",\n'
            '       "technique_id": "MITRE Technique ID (e.g., T1190, T1110)",\n'
            '       "technique_name": "MITRE Technique Name (e.g., Exploit Public-Facing Application)"\n'
            '     }\n'
            '  ],\n'
            '  "confidence_score": 0.95,  # Float value between 0.0 and 1.0\n'
            '  "evidence": ["List of log lines, strings, hashes, or indicators matching the threat"],\n'
            '  "recommendations": ["Actionable remediation step 1", "Actionable remediation step 2"],\n'
            '  "root_cause": "Short summary of why this attack succeeded or was attempted"\n'
            "}\n\n"
            "Do NOT include any chat preamble, greeting, markdown blocks, or extra text. ONLY return the valid JSON."
        )

        user_content = (
            f"=== SECURITY INPUT TO ANALYZE ===\n{security_input}\n\n"
            f"=== RETRIEVED THREAT INTELLIGENCE (RAG CONTEXT) ===\n{retrieved_context}\n\n"
            "Analyze the above input. Perform detection, identify MITRE techniques, determine severity, list evidence and recommend actions. Output JSON."
        )

        try:
            url = f"{self.api_url}/api/chat"
            payload = {
                "model": self.model_name,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content}
                ],
                "stream": False,
                "format": "json"  # Instruct Ollama to output valid JSON
            }
            
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST"
            )
            
            with urllib.request.urlopen(req, timeout=300) as response:
                res_data = json.loads(response.read().decode("utf-8"))
                response_text = res_data["message"]["content"]
                
                # Parse the inner JSON response generated by the LLM
                analysis_result = json.loads(response_text)
                
                confidence = analysis_result.get("confidence_score", 0.85)
                
                return {
                    "status": "success",
                    "confidence": confidence,
                    "result": analysis_result
                }
                
        except json.JSONDecodeError as je:
            return {
                "status": "error",
                "confidence": 0.0,
                "error": f"Failed to parse LLM response as JSON: {je}",
                "raw_response": response_text if 'response_text' in locals() else None,
                "result": {
                    "threat_detected": "Error during analysis parsing.",
                    "classification": "Error",
                    "severity": "Info",
                    "mitre_mapping": [],
                    "confidence_score": 0.0,
                    "evidence": [],
                    "recommendations": ["Verify local Ollama service status and check log files."],
                    "root_cause": str(je)
                }
            }
        except Exception as e:
            return {
                "status": "error",
                "confidence": 0.0,
                "error": f"Connection error to Ollama model {self.model_name}: {e}",
                "result": {
                    "threat_detected": "Ollama LLM connection offline.",
                    "classification": "Error",
                    "severity": "Info",
                    "mitre_mapping": [],
                    "confidence_score": 0.0,
                    "evidence": [],
                    "recommendations": [
                        "Ensure Ollama is running.",
                        f"Verify '{self.model_name}' has been pulled using 'ollama pull {self.model_name}'."
                    ],
                    "root_cause": str(e)
                }
            }
